import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Web3ContextProvider from "@/context/WagmiProvider";
import { headers } from "next/headers";
import { Provider } from "@/components/ui/provider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const cookies = headersList.get("cookie");

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Web3ContextProvider cookies={cookies}>
          <Provider>{children}</Provider>
        </Web3ContextProvider>
      </body>
    </html>
  );
}
